[package]
name = "ps-snippets"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[package.metadata.docs.rs]
rustdoc-args = [ "--html-in-header", "./katex.html" ]

[dependencies]
io = { path = "crates/io" }

# number
ord_f64 = { path = "crates/number/ord_f64" }

# graph
dijkstra = { path = "crates/graph/dijkstra" }

[lints.clippy]
