[package]
name = "dijkstra"
version = "0.1.0"
edition = "2015"
license = "CC0-1.0"

[dependencies]

[lints.clippy]
pedantic = { level = "warn", priority = -1 }
missing_panics_doc = "allow" # use ⚠️ instead
len_without_is_empty = "allow" # no need

nursery = { level = "warn", priority = -1 }
